mutation createUser($userInfo: UserInput!){
  user: signUpUser(userNew: $userInfo){ 
      _id
      firstName
      lastName
      email
  }
}

{
  "userInfo": {
    "firstName": "Muhammad",
    "lastName": "Hasan",
    "email": "hasan@gmail.com",
    "password": "Hasan123"
  }
}
---------------------------------------------------------------

mutation singInUser($userInfo: AuthInput!){
    userToken: signInUser(userSign: $userInfo){
      token
    } 
}

{
  "userInfo": {
    "email": "hasan@gmail.com",
    "password": "Hasan123"
  }
}

Response:- 
{
  "data": {
    "userToken": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NTgxYjBiYTc5MTViYjJjZjk1YjZlZTUiLCJpYXQiOjE3MDMwMDIzNzAsImV4cCI6MTcwMzQzNDM3MH0.aweT1AaXGeF80A1Cl2MiW8UVM71SyGBZ1CyWsz0ls1A"
    }
  }
}
---------------------------------------------------------------

mutation DoQuote{
  Quote: createQuote(name: "The Thing that works for you is the best for you")
}

Header :- 
Authorization = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTgxYjBiYTc5MTViYjJjZjk1YjZlZTUiLCJpYXQiOjE3MDMwNzY5OTMsImV4cCI6MTcwMzE2MzM5M30.NXeOCUu23QC8Obb4p3wINSA46Lca72cbLMUonUJAnVU"

Response:- {
  "data": {
    "Quote": "Quote saved successfully !"
  }
}
-----------------------------------------------------------------

query GetAllQuote{
  quotes {
    name
    by {
      _id
      firstName
      lastName
    }
  }
}

Response :- {
  "data": {
    "quotes": [
      {
        "name": "This is me Hasan and doing testing",
        "by": {
          "_id": "6581c5271efdad025cd6fb12",
          "firstName": "Umer",
          "lastName": "Ali"
        }
      },
      {
        "name": "The Thing that works for you is the best for you",
        "by": {
          "_id": "6581b0ba7915bb2cf95b6ee5",
          "firstName": "Muhammad",
          "lastName": "Hasan"
        }
      }
    ]
  }
}
--------------------------------------------------------------------------

query MyProfile{
  user: myProfile {
    _id
    email
    firstName
    lastName
  }
}

Response:-{
  "data": {
    "user": {
      "_id": "6585b0536a0d9bc53639e52d",
      "email": "saad@gmail.com",
      "firstName": "Saad",
      "lastName": "Zubair"
    }
  }
}

Header:-
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTg1YjA1MzZhMGQ5YmM1MzYzOWU1MmQiLCJpYXQiOjE3MDMyNjAyNjgsImV4cCI6MTcwMzM0NjY2OH0.YQncomiRDuLHgOTabZ1ItuBBRk5IOCI9I5RpGGfg6YI
--------------------------------------------------------------------------------

query GetUserById($userId: ID!){
  user(_id: $userId){
    firstName
    lastName
    email
    quotes {
      name
      by {
        _id
      }
    }
  }
}

Variables:- {
   "userId": "6585b0536a0d9bc53639e52d"
}

Response :- {
  "data": {
    "user": {
      "firstName": "Saad",
      "lastName": "Zubair",
      "email": "saad@gmail.com",
      "quotes": [
        {
          "name": "Allah will do everything right !",
          "by": {
            "_id": "6585b0536a0d9bc53639e52d"
          }
        },
        {
          "name": "Always be Humble!",
          "by": {
            "_id": "6585b0536a0d9bc53639e52d"
          }
        }
      ]
    }
  }
}
-------------------------------------------------------------------------------------